# -*- mode: ruby -*-
# vi: set ft=ruby :

VMUSER="vagrant"
SF="../"
ARDUINO_VERS="1.8.12"

# Add more rights to the user
$script_updateuser= <<SCRIPT
cp -pr /home/vagrant/.ssh /home/#{VMUSER}/
echo "%#{VMUSER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/#{VMUSER}
addgroup #{VMUSER} vboxsf
addgroup #{VMUSER} dialout
SCRIPT

# Install stuff
#NOTE: firefox link so web browser icon works (it points to this by default)
$script_installsw = <<SCRIPT
apt-get update
apt-get -y install python-pip
apt-get -y install python3-pip
apt-get -y install gnome-system-monitor
apt-get -y install mosquitto-clients
SCRIPT


# Install ESP and Arduino utils
$script_installesp = <<SCRIPT
pip install esptool

wget --progress=bar:force http://downloads.arduino.cc/arduino-#{ARDUINO_VERS}-linux64.tar.xz -P /home/#{VMUSER}/Downloads
tar xvf /home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}-linux64.tar.xz -C /home/#{VMUSER}/Downloads
rm /home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}-linux64.tar.xz

su -l #{VMUSER} bash -c "/home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}/arduino --pref \\"boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json\\" --save-prefs"
su -l #{VMUSER} bash -c "/home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}/arduino --install-boards esp8266:esp8266 --save-prefs"
su -l #{VMUSER} bash -c "/home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}/arduino --install-library \\"DHT sensor library\\""
su -l #{VMUSER} bash -c "/home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}/arduino --install-library \\"Adafruit Unified Sensor\\""
su -l #{VMUSER} bash -c "/home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}/arduino --install-library \\"PubSubClient\\""

chown -R #{VMUSER}:#{VMUSER} /home/#{VMUSER}
su -l #{VMUSER} bash -c "ln -s /home/#{VMUSER}/Downloads/arduino-#{ARDUINO_VERS}/arduino /home/#{VMUSER}/Desktop/Arduino"
SCRIPT

# Configure share - make it easier to find
$script_configshare = <<SCRIPT
ln -s /vm_global_share /home/#{VMUSER}/workspace
SCRIPT

Vagrant.configure("2") do |config|

    #Make sure we do not login using the 'vagrant' user
    VAGRANT_COMMAND = ARGV[0]
    if VAGRANT_COMMAND == "ssh"
          config.ssh.username = VMUSER
    end

    config.vm.box = "axcxl/debian11_xfce"

    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = 4096
        vb.cpus = 4
    end

    config.vm.define "devesp" do |machine|

        machine.vm.hostname = 'devesp'

        # Create the additional user
        machine.vm.provision "shell", inline: $script_updateuser 

        # Install SW
        machine.vm.provision "shell", inline: $script_installsw

        # Install ESP dev tools
        machine.vm.provision "shell", inline: $script_installesp

        # configure share
        machine.vm.provision "shell", inline: $script_configshare
    end

    #Warning: issue with shared folder and vagrant.
    #Workaround: vagrant up -> wait until error -> run `vagrant up --provision` once -> wait to finish and manually
    #mount the shared folder to /vm_global_share. Only run provision once when the VM is created.
    #config.vm.synced_folder "#{SF}", "/vm_global_share", group: "vboxsf", mount_options: ["dmode=775,fmode=664"]

end

