# -*- mode: ruby -*-
# vi: set ft=ruby :

SF_NR="../conf_nodered"
SF_DM="../conf_domoticz"

# Install stuff
$script_installsw = <<SCRIPT
apt-get update

apt-get install -y ntp mosquitto
SCRIPT


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/contrib-buster64"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  config.vm.network "public_network", bridge: "eth0"

  # Docker stuff
  config.vm.provision "docker" do |d|
    # Nodered for mqtt -> json translation
    d.run "nodered/node-red",
      args: "-it -p 1880:1880 --name mynodered -v /home/vagrant/conf_nodered:/data"

    d.run "linuxserver/domoticz",
      args: "--name domoticz -p 8080:8080 -e PUID=1000 -e PGID=1000 -v /home/vagrant/conf_domoticz:/config"
  end

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = 2048
    vb.cpus = 1
  end
  
  config.vm.define "esenz" do |machine|
	machine.vm.hostname = 'esenz'
	
	# Install SW
	machine.vm.provision "shell", inline: $script_installsw
  end
    
  config.vm.synced_folder "#{SF_NR}", "/home/vagrant/conf_nodered", group: "vboxsf", mount_options: ["dmode=775,fmode=664"]
  config.vm.synced_folder "#{SF_DM}", "/home/vagrant/conf_domoticz", group: "vboxsf", mount_options: ["dmode=775,fmode=664"]


end
